# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1=np.arange(10).reshape(2,5)
arr2=np.ones((2,5),dtype=int)
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr1=np.arange(10).reshape(2,5)
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr1=np.arange(15).reshape(3,5)
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr1=np.arange(15)
arr1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
arr1=np.arange(25).reshape(5,5)
np.square(arr1)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [13]:
arr=np.array(np.random.randn(5,6)*10,dtype=int)
print(arr)
print(np.mean(arr))

[[-10 -14 -14   4  25  -5]
 [  6   0  18  -3   0  -8]
 [ -7   4  -4  -1 -12  -3]
 [ -1   8  -5  -6   2  -1]
 [  3  17 -24 -14   5   1]]
-1.3


## Question:9

### Find the standard deviation of the previous array in Q8?

In [15]:
np.std(arr)

10.00383259889262

## Question:10

### Find the median of the previous array in Q8?

In [16]:
np.median(arr)

-1.0

## Question:11

### Find the transpose of the previous array in Q8?

In [18]:
arr.transpose()

array([[-10,   6,  -7,  -1,   3],
       [-14,   0,   4,   8,  17],
       [-14,  18,  -4,  -5, -24],
       [  4,  -3,  -1,  -6, -14],
       [ 25,   0, -12,   2,   5],
       [ -5,  -8,  -3,  -1,   1]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [20]:
arr=np.array(np.random.randn(4,4)*10,dtype=int)
print(arr)
print(np.trace(arr))

[[ -7   1 -11  11]
 [  7   0   1  -9]
 [  6   8  -6   0]
 [ -4  -2  -3  15]]
2


## Question:13

### Find the determinant of the previous array in Q12?

In [21]:
from numpy import linalg
np.linalg.det(arr)

-5794.000000000006

## Question:14

### Find the 5th and 95th percentile of an array?

In [22]:
arr=np.arange(10)
print(arr)
print()
print(np.percentile(arr,5))
print()
print(np.percentile(arr,95))

[0 1 2 3 4 5 6 7 8 9]

0.45

8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [24]:
arr=np.arange(15).reshape(3,5)
print(np.isnan(arr))

[[False False False False False]
 [False False False False False]
 [False False False False False]]
